using Microsoft.Data.Sqlite;
using ClosedXML.Excel;
namespace SamboSecretary;
public record Athlete(long Id,string FullName,string Team,string Discipline,string Gender,string AgeGroup,string WeightCategory,double? ActualWeight,string Status);
public sealed class Database {
 public string FileName{get;} public Database(string file){FileName=file;Directory.CreateDirectory(Path.GetDirectoryName(file)!);Init();}
 SqliteConnection Open(){var c=new SqliteConnection($"Data Source={FileName}");c.Open();return c;}
 void Init(){using var c=Open();using var q=c.CreateCommand();q.CommandText=@"CREATE TABLE IF NOT EXISTS athletes(id INTEGER PRIMARY KEY,full_name TEXT NOT NULL,team TEXT,discipline TEXT,gender TEXT,age_group TEXT,weight_category TEXT,actual_weight REAL,status TEXT DEFAULT 'Заявлен');CREATE TABLE IF NOT EXISTS judges(id INTEGER PRIMARY KEY,name TEXT NOT NULL,region TEXT,category TEXT,role TEXT);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,ts TEXT NOT NULL,action TEXT NOT NULL);";q.ExecuteNonQuery();}
 public void Audit(string s){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO audit(ts,action) VALUES($t,$a)";q.Parameters.AddWithValue("$t",DateTime.Now.ToString("s"));q.Parameters.AddWithValue("$a",s);q.ExecuteNonQuery();}
 public void AddAthlete(string name,string team="",string discipline="Спортивное самбо",string gender="",string age="",string weight=""){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO athletes(full_name,team,discipline,gender,age_group,weight_category) VALUES($n,$t,$d,$g,$a,$w)";q.Parameters.AddWithValue("$n",NameNormalizer.Normalize(name));q.Parameters.AddWithValue("$t",team);q.Parameters.AddWithValue("$d",discipline);q.Parameters.AddWithValue("$g",gender);q.Parameters.AddWithValue("$a",age);q.Parameters.AddWithValue("$w",weight);q.ExecuteNonQuery();Audit("Добавлен спортсмен "+NameNormalizer.Normalize(name));}
 public List<Athlete> Athletes(){using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT id,full_name,team,discipline,gender,age_group,weight_category,actual_weight,status FROM athletes ORDER BY full_name";using var r=q.ExecuteReader();var x=new List<Athlete>();while(r.Read())x.Add(new(r.GetInt64(0),r.GetString(1),r.IsDBNull(2)?"":r.GetString(2),r.IsDBNull(3)?"":r.GetString(3),r.IsDBNull(4)?"":r.GetString(4),r.IsDBNull(5)?"":r.GetString(5),r.IsDBNull(6)?"":r.GetString(6),r.IsDBNull(7)?null:r.GetDouble(7),r.IsDBNull(8)?"":r.GetString(8)));return x;}
 public void SetWeigh(long id,double kg){using var c=Open();using var q=c.CreateCommand();q.CommandText="UPDATE athletes SET actual_weight=$w,status='Допущен' WHERE id=$id";q.Parameters.AddWithValue("$w",kg);q.Parameters.AddWithValue("$id",id);q.ExecuteNonQuery();Audit($"Взвешивание {id}: {kg} кг");}
}
public static class ExcelImporter {
 public static List<Dictionary<string,string>> Read(string path){using var wb=new XLWorkbook(path);var ws=wb.Worksheets.First();var used=ws.RangeUsed();if(used==null)return[];var h=used.FirstRow().Cells().Select(c=>c.GetString().Trim()).ToArray();var rows=new List<Dictionary<string,string>>();foreach(var row in used.RowsUsed().Skip(1)){var d=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);for(int i=0;i<h.Length;i++)if(h[i]!="")d[h[i]]=row.Cell(i+1).GetFormattedString();rows.Add(d);}return rows;}
 public static string ExtractName(Dictionary<string,string> r){string Get(params string[] k)=>k.Select(z=>r.FirstOrDefault(x=>x.Key.Contains(z,StringComparison.OrdinalIgnoreCase)).Value).FirstOrDefault(v=>!string.IsNullOrWhiteSpace(v))??"";var whole=Get("фио","ф.и.о","спортсмен");return whole!=""?NameNormalizer.Normalize(whole):NameNormalizer.Normalize(Get("фамил"),Get("имя"),Get("отчеств"));}
}