using System.Drawing.Printing;
namespace SamboSecretary;
static class Program{[STAThread]static void Main(){ApplicationConfiguration.Initialize();Application.Run(new MainForm());}}
public sealed class MainForm:Form{
 readonly string root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SamboSecretary");readonly Database db;readonly DataGridView grid=new(){Dock=DockStyle.Fill,ReadOnly=true,SelectionMode=DataGridViewSelectionMode.FullRowSelect};readonly ToolStrip bar=new(){Dock=DockStyle.Top};
 public MainForm(){Text="Самбо-секретарь 1.0";Width=1200;Height=760;db=new Database(Path.Combine(root,"sambo.db"));Controls.Add(grid);Controls.Add(bar);Button("Добавить",Add);Button("Импорт Excel",Import);Button("Взвешивание",Weigh);Button("Жеребьёвка",Draw);Button("Печать",Print);Button("Резервная копия",Backup);Refresh();}
 void Button(string t,EventHandler e){var b=new ToolStripButton(t);b.Click+=e;bar.Items.Add(b);}void Refresh()=>grid.DataSource=db.Athletes().Select(x=>new{x.Id,ФИО=x.FullName,Команда=x.Team,Дисциплина=x.Discipline,Пол=x.Gender,Возраст=x.AgeGroup,Категория=x.WeightCategory,Вес=x.ActualWeight,Статус=x.Status}).ToList();
 void Add(object? s,EventArgs e){var name=Microsoft.VisualBasic.Interaction.InputBox("ФИО","Добавление спортсмена");if(name!=""){db.AddAthlete(name);Refresh();}}
 void Import(object? s,EventArgs e){using var o=new OpenFileDialog{Filter="Excel (*.xlsx)|*.xlsx"};if(o.ShowDialog()!=DialogResult.OK)return;try{var rows=ExcelImporter.Read(o.FileName);int n=0;foreach(var r in rows){var name=ExcelImporter.ExtractName(r);if(name=="")continue;string V(string k)=>r.FirstOrDefault(x=>x.Key.Contains(k,StringComparison.OrdinalIgnoreCase)).Value??"";db.AddAthlete(name,V("команд"),V("дисцип"),V("пол"),V("возраст"),V("катег"));n++;}MessageBox.Show($"Импортировано: {n}");Refresh();}catch(Exception ex){MessageBox.Show(ex.Message,"Ошибка");}}
 void Weigh(object? s,EventArgs e){if(grid.CurrentRow?.Cells[0].Value is not long id)return;var v=Microsoft.VisualBasic.Interaction.InputBox("Фактический вес, кг","Взвешивание");if(double.TryParse(v.Replace(',','.'),System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out var kg)){db.SetWeigh(id,kg);Refresh();}}
 void Draw(object? s,EventArgs e){var ids=db.Athletes().Where(x=>x.Status=="Допущен").Select(x=>x.Id).ToList();if(ids.Count<2){MessageBox.Show("Недостаточно допущенных участников");return;}var systems=string.Join(", ",TournamentEngine.Allowed(ids.Count));if(ids.Count>=8){var size=TournamentEngine.BracketSize(ids.Count);var slots=TournamentEngine.Draw(ids,size,DrawMode.FullAuto);MessageBox.Show($"Система: {systems}\nСетка: {size}\n"+string.Join("\n",slots.Select((x,i)=>$"{i+1}: {(x?.ToString()??"СВОБОДНО")}")),"Предварительная жеребьёвка");}else MessageBox.Show($"Доступные системы: {systems}","Жеребьёвка");}
 void Backup(object? s,EventArgs e){var d=Path.Combine(root,"Backups");Directory.CreateDirectory(d);var p=Path.Combine(d,$"sambo_{DateTime.Now:yyyyMMdd_HHmmss}.db");File.Copy(db.FileName,p,true);MessageBox.Show(p);}
 void Print(object? s,EventArgs e){var a=db.Athletes();int i=0;var pd=new PrintDocument();pd.PrintPage+=(s,e)=>{float y=40;e.Graphics!.DrawString("САМБО — СПИСОК УЧАСТНИКОВ",new Font("Arial",14,FontStyle.Bold),Brushes.Black,40,y);y+=35;while(i<a.Count&&y<e.MarginBounds.Bottom-25){var x=a[i++];e.Graphics.DrawString($"{i}. {x.FullName}  {x.Team}  {x.WeightCategory}  {x.Status}",new Font("Arial",10),Brushes.Black,40,y);y+=22;}e.HasMorePages=i<a.Count;};using var p=new PrintPreviewDialog{Document=pd,Width=1000,Height=700};p.ShowDialog();}
}